name: Publish Docker image

on:
  workflow_run:
    workflows: ["continuous integration"]
    branches:
      - main
      - master
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq 
          sudo chmod +x /usr/bin/yq

      - name: Run docker tag sh and export var form config.yml
        run: |
          ./docker_tag.sh

      - name: Load variables from .env file
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Debug
        run: |
          DOCKER_HUB_USERNAME="$DOCKER_HUB_USERNAME"
          DOCKER_REPO_NAME="$DOCKER_REPO_NAME"
          NEW_TAG="$NEW_TAG"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $DOCKER_HUB_USERNAME/$DOCKER_REPO_NAME:$NEW_TAG
