name: Publish Docker image

on:
  workflow_run:
    workflows: ["continuous integrationt"]
    branches:
      - main
      - master
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install jq & yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          sudo apt install -y jq 

      - name: Run docker tag sh and export var form config.yml
        run: |
          source ./docker_tag.sh
      
      - name: Debug
        run: |
          echo "DOCKER_HUB_USERNAME: ${{ env.DOCKER_HUB_USERNAME }}"
          echo "DOCKER_REPO_NAME: ${{ env.DOCKER_REPO_NAME }}"
          echo "NEW_TAG: ${{ env.NEW_TAG }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ env.NEW_TAG }}
